### ISSUE TITLE
Update to babel 6

### ISSUE THREAD

**Issue by pasviegas** [pocotan001/react-styleguide-generator#19]
Now that babel 6 is out, would be good to upgrade styleguide-generator to use the new version

**Comment by theogravity** [comment]
Hi @pasviegas, I have a version that uses webpack + babel 6 here:

https://github.com/theogravity/react-styleguide-generator-alt

**Comment by gabrielpugliese-luizalabs** [comment]
@theogravity babel v6.4 introduced the semicolon madness to static vars and it's complaining when I try to run rsg-alt. Does it have anything to do with rsg-alt or it's probably my project?

**Comment by theogravity** [comment]
I want to say it's probably your project. I made sure babel 6.3 was being used (because the styleguide examples would also throw errors during babel transpilation under 6.4).

Do you want to paste in your package.json? You can also figure out what babel libs are being used + versions by doing `npm ls | grep babel`.

**Comment by azu** [comment]
This issue seem to be resolved by #24

**Comment by 1000ch** [comment]
Fixed in newest version.
